### ISSUE TITLE
Improve the exercise

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m1-evaluacion-intermedia-valerialp#1]
Really cool job @valerialp  !!!

Here you have some tips to improve the exercise:

- [x] Fix the language and the meta title of the page
- [x] Move the font CSS before your main CSS
- [x] Improve hierarchy adding more common styles to `body` tag as font-size, font-family, font-weight, color, background-color
- [x] Finish the main title styles: the typography should be bolder
- [ ] Try to use imperative for your commit messages. Ex. - > Fix central text
- [x] Organize your files in folders, you have a guide to help you with that here --> https://books.adalab.es/materiales-front-end-f/modulo-1.-hola-mundo/1_1_intro_a_la_web#notas-finales-sobre-como-organizar-nuestro-proyecto

Let me know if you have any doubts ;)

Go for it!!

**Comment by valerialp** [comment]
I think I make all the improvements if something goes wrong please tell me

**Comment by nasivuela** [comment]
Well done @valerialp!!

There is a little detail to make it perfect, `Diversidad` word looks slightly moved to the right on the tablet version. 
Anyway, that's a really good job, you got it!

![](https://media.giphy.com/media/RrVzUOXldFe8M/giphy.gif)
